go install -v github.com/acroca/go-symbols
go install -v github.com/alecthomas/gometalinter
go install -v github.com/cweill/gotests/...
go install -v github.com/davidrjenni/reftools/cmd/fillstruct
go install -v github.com/derekparker/delve/cmd/dlv
go install -v github.com/fatih/gomodifytags
go install -v github.com/golang/lint/golint
go install -v github.com/haya14busa/goplay/cmd/goplay
go install -v github.com/josharian/impl
go install -v github.com/nsf/gocode
go install -v github.com/ramya-rao-a/go-outline
go install -v github.com/rogpeppe/godef
go install -v github.com/sourcegraph/go-langserver
go install -v github.com/sqs/goreturns
go install -v github.com/tylerb/gotype-live
go install -v github.com/uudashr/gopkgs/cmd/gopkgs
go install -v github.com/zmb3/goinstalldoc
go install -v golang.org/x/tools/cmd/godoc
go install -v golang.org/x/tools/cmd/goimports
go install -v golang.org/x/tools/cmd/gorename
go install -v golang.org/x/tools/cmd/guru
go install -v honnef.co/go/tools/...
